### PR TITLE
Sort Shortcuts Section (ORM) Alphabetically

### PR DESCRIPTION
**Pull request by mrhrifat**

### CODE REVIEW

**Comment by mrhrifat** [comment]
@mehtaAnsh Did you notice it?

**Comment by mrhrifat** [comment]
What should I do now?

**Comment by mrhrifat** [comment]
@mehtaAnsh  The pull request is still open. You didn't give any feedback that, If is it marge-able with branch then merge it otherwise request for changes else close it.

**Comment by mehtaAnsh** [comment]
> @mehtaAnsh The pull request is still open. You didn't give any feedback that, If is it marge-able with branch then merge it otherwise request for changes else close it.

Hi, I will merge the branch by 12 hours. Sorry for the inconvenience. Keep contributing :)

**Review by mehtaAnsh — APPROVED** [review]
Thanks for contributing :)

**Pull request merged**
