### PR TITLE
Added A New And Improved NuxtJS Badge

### PR DESCRIPTION
**Pull request by NawrasseDahman**

### CODE REVIEW

**Review by kohasummons — APPROVED** [review]
🍖 Looks good to me. Thanks for contributing @NawrasseDahman ✨

**Comment by NawrasseDahman** [comment]
So Is Going To Be Murged Or Not, Because I Honesty Worked Hard For It

**Comment by NawrasseDahman** [comment]
🥺

**Review by Ileriayo — APPROVED** [review]
LGTM.

Thanks for improving this badge, @NawrasseDahman!

**Pull request merged**
