### PR TITLE
Added Twilio badge

### PR DESCRIPTION
**Pull request by rudrakshi99**
## Description
Added a Badge for Twilio.
Issue: #476 
## Info

Badge Name:  Twilio

Badge Category: Others

Background Color: #F22F46

Logo Color: white

## Badge Url: 
Twilio 

`https://img.shields.io/badge/Twilio-F22F46?style=for-the-badge&logo=Twilio&logoColor=white`

### CODE REVIEW

**Review by allankildare — COMMENTED** [review]
Hi @rudrakshi99,
I noticed you made many changes, is that correct?
For example, I noticed that you add and remove some blank spaces, maybe the settings you use or lint fixed it automatically, what do you think?

**Comment by rudrakshi99** [comment]
Hi @allankildare, It is because I have installed the Prettier Extension in VS code editor. It auto-indents the code.

**Review by Ileriayo — CHANGES_REQUESTED** [review]
Too many line changes. 

Kindly update your PR to include only the intended change.

Thanks.

**Comment by rudrakshi99** [comment]
I have opened a new PR. Please refer to [this](https://github.com/Ileriayo/markdown-badges/pull/679)

**Pull request closed without merging**
