### PR TITLE
closes #482 #650 #718 and first part of #714

### LINKED ISSUE #482: Badge Request - GitBook
A documentation platform

https://www.gitbook.com/

### PR DESCRIPTION
**Pull request by CleverLemming1337**
## Info

|Name|Category|Background Color|Logo Color|
|:--:|:--:|:--:|:--:|
GitBook | Documentation Platforms | `#000000` | `#FFFFFF`
GitHub Copilot|Artificial Intelligence and Bots| `#8957E5`|`#FFFFFF`
ReadTheDocs | Documentation Platforms | `#000000` | `#FFFFFF` |
Streamlit | Frameworks, Platforms and Libraries | `#FE4B4B` | `#FFFFFF`
 

## Preview

| Badge | url |
| ----- | --- |
| GitBook | `GitBook` |
| GitHub Copilot | `GitHub Copilot`|
Streamlit | `Streamlit`
ReadTheDocs | `ReadTheDocs` |

### CODE REVIEW

**Comment by CleverLemming1337** [comment]
closes #718

**Comment by CleverLemming1337** [comment]
closes #650

**Review by Ileriayo — CHANGES_REQUESTED** [review]
Resolve merge conflicts.

**Comment by CleverLemming1337** [comment]
> Resolve merge conflicts.

Done

**Review by Ileriayo — APPROVED** [review]

**Pull request merged**
