### PR TITLE
Add RStudio IDE badge to IDEs/Editors 

### PR DESCRIPTION
**Pull request by ndbzika**
I think it'll be nice add this IDE because it works with the programming language R.

### CODE REVIEW

**Review by kohasummons — CHANGES_REQUESTED** [review]
@ndbzika, This is awesome! We just need to fix a tiny thing and we can merge this. Check out the screenshot.

Screenshot: 
image

Notice the word salad beneath the RStudio Badge.  Could you please clean it up a bit? 👍🏽

**Comment by ndbzika** [comment]
@kohasummons It's all okay now 😃

**Comment by kohasummons** [comment]
That was super fast @ndbzika  :zap:

I'm away from my PC atm. Would review it once I'm able to. Thank you, @ndbzika .

**Review by kohasummons — APPROVED** [review]
@ndbzika, you rock! 👏🏽

**Pull request merged**
