### PR TITLE
Add alt attribute to badges

### PR DESCRIPTION
**Pull request by B3ns44d**
Add the alt attribute to all badges

### Gaming
| Name       | Badge                                                                                                                      | Markdown                                                                                                                     |
| ---------- | -------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------- |
| Unreal Engine    |  | `` |

### Gaming
| Name       | Badge                                                                                                                      | Markdown                                                                                                                     |
| ---------- | -------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------- |
| Unreal Engine    | Unreal Engine | `Unreal Engine` |

### CODE REVIEW

**Comment by B3ns44d** [comment]
Added a new badges pack

-     Social
-     Store
-     Music
-     Funding
-     Operating System

**Review by Ileriayo — CHANGES_REQUESTED** [review]
This is absolutely awesome, Bensaad!
It helps with accessibility (a11y).
Kindly resolve the merge conflicts and I'll be happy to merge.

**Comment by B3ns44d** [comment]
I am delighted to contribute to this project.
all conflicts have been fixed and I think ready to merge

**Review by Ileriayo — APPROVED** [review]
Awesome!

**Pull request merged**
