### PR TITLE
feat: add GraphQL badge

### PR DESCRIPTION
**Pull request by kevinadhiguna**
I added a GraphQL badge which is I think categorized as `API` but I put it on `Other`.

### CODE REVIEW

**Review by yezz123 — COMMENTED** [review]
Can u add a .NET Framework Badge ?

**Comment by kevinadhiguna** [comment]
> Can u add a .NET Framework Badge ?

Hi @yezz123 , I just made a PR for .NET framework badge (#32). If that is not what you wanted, please let me know. Thanks :)

**Comment by kevinadhiguna** [comment]
Hi @Ileriayo , if you do not mind, please review my Pull Requests at your earliest convenience. Thank you.

**Review by Ileriayo — APPROVED** [review]
Thanks for adding another badge!

**Pull request merged**
