### PR TITLE
updating android studio and firebase layout

### PR DESCRIPTION
**Pull request by AnderMendoza**
I have changed the design to better distinguish the tool icon next to a background that better accompanies the badge.

I leave the comparisons for your analysis 👇

NEW:

Firebase 
Android Studio

OLD:

Firebase
Android Studio

### CODE REVIEW

**Review by kohasummons — COMMENTED** [review]
Hey @AnderMendoza, this looks better. Thanks for helping out. Look forward to your next PRs. :rocket: 

what do you think about using white for the android  studio logo?

**Comment by AnderMendoza** [comment]
sure, now I change it for the revision

**Review by AnderMendoza — COMMENTED** [review]
Change Android Studio icon color to white

**Review by allankildare — APPROVED** [review]
The white logo looks really better, what do you think @kohasummons?

**Comment by Ileriayo** [comment]
Thanks for contributing!

**Pull request merged**
