### PR TITLE
Make Stylus badge orange

### PR DESCRIPTION
**Pull request by spenserblack**
The image URL did not match what the actual rendered image was in the README. This makes them match.

***

Edit: Looks like it was added in cc162cc3. I'm not sure which color the original author intended to be the correct one.
I actually think the color should be a shade of orange like `#ff6347`, like in [their website](https://stylus-lang.com/). Please let me know if I should make the badge that color instead :slightly_smiling_face:

### CODE REVIEW

**Review by mehtaAnsh — APPROVED** [review]
Thanks for bringing this up. Keep contributing!

**Comment by mehtaAnsh** [comment]
> 
> 
> The image URL did not match what the actual rendered image was in the README. This makes them match.
> 
> Edit: Looks like it was added in [cc162cc](https://github.com/Ileriayo/markdown-badges/commit/cc162cc34d49865c53294c6fb39b5fe234f81c6b). I'm not sure which color the original author intended to be the correct one.
> I actually think the color should be a shade of orange like `#ff6347`, like in [their website](https://stylus-lang.com/). Please let me know if I should make the badge that color instead 🙂

Sure, go ahead and fix the badge according to the logo color. That would be great!

**Comment by spenserblack** [comment]
>Sure, go ahead and fix the badge according to the logo color. That would be great!

Done 👍

**Review by mehtaAnsh — APPROVED** [review]
Thanks for fixing. Keep contributing!

**Pull request merged**
