### PR TITLE
Filament Badge 

### PR DESCRIPTION
**Pull request by OmarFaig**
## Info
Name	Category	        Background Color	Logo Color
Filament	Framework	#FFAA00	                #000000

## Preview

| Badge | url |
| Filament                                               | `Filament`

### CODE REVIEW

**Review by Ileriayo — CHANGES_REQUESTED** [review]
Resolve merge conflicts.

**Review by Ileriayo — CHANGES_REQUESTED** [review]
There's a lot of line changes in this PR.

Kindly ensure that only the lines that have to do with the PR are affected.

**Comment by OmarFaig** [comment]
Just created a new PR. I only added one element but got merge conflict for other badges too.So I pushed and pulled only My changes now

**Comment by Ileriayo** [comment]
This PR is now a duplicate of #747 
Closing this PR

**Pull request closed without merging**
