### PR TITLE
Lenovo badge added `new-badge`

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**

### CODE REVIEW

**Review by Ileriayo — CHANGES_REQUESTED** [review]
Hi, and thanks for contributing!

Kindly resolve the merge conflicts, so that your PR can be merged.

Thanks.

**Comment by gurjeetsinghvirdee** [comment]
> Hi, and thanks for contributing!
> 
> Kindly resolve the merge conflicts, so that your PR can be merged.
> 
> Thanks.

I didn't see any conflicts here, If I'm wrong tell me what to change I will change it

**Comment by Ileriayo** [comment]
When new code (e.g., from other PRs) has been merged into the default branch, you'll need to sync your branch with the default branch so that your branch would also have the latest code. If you do not do this, many times, there will be a merge conflict trying to merge a stale branch.
So what you need to do is to switch to your PR branch and rebase/merge the latest changes into your branch before pushing.
> I didn't see any conflicts here, If I'm wrong tell me what to change I will change it

**Comment by Ileriayo** [comment]
Just to give you a view, here's how it looks on my end.
Screenshot 2022-01-11 at 21 25 51

**Comment by gurjeetsinghvirdee** [comment]
> When new code (e.g., from other PRs) has been merged into the default branch, you'll need to sync your branch with the default branch so that your branch would also have the latest code. If you do not do this, many times, there will be a merge conflict trying to merge a stale branch. So what you need to do is to switch to your PR branch and rebase/merge the latest changes into your branch before pushing.
> 
> > I didn't see any conflicts here, If I'm wrong tell me what to change I will change it

yeah I Understand that's my mistake, I will close this issue and open new one with same badge

**Pull request closed without merging**
