### PR TITLE
Added new badges and "search engine" section

### PR DESCRIPTION
**Pull request by Abdullah-Alhariri**

### CODE REVIEW

**Review by JakyeRU — CHANGES_REQUESTED** [review]
Please make sure the badges are ordered alphabetically.

**Review by mehtaAnsh — CHANGES_REQUESTED** [review]
Hi @Abdullah-Alhariri , thanks for contributing a variety of badges. Can you please remove Microsoft bing from the browsers section? It is a search engine, so should not come under Browsers section. Maybe you can create a new section for search engines and add different badges like DuckDuckGo and Google. 

Thanks! :)

**Comment by Abdullah-Alhariri** [comment]
> Hi @Abdullah-Alhariri , thanks for contributing a variety of badges. Can you please remove Microsoft bing from the browsers section? It is a search engine, so should not come under Browsers section. Maybe you can create a new section for search engines and add different badges like DuckDuckGo and Google.
> 
> Thanks! :)

oh yeah, I totally forgot that.

**Review by mehtaAnsh — APPROVED** [review]
The changes look great. Thanks for contributing!

**Pull request merged**
