### PR TITLE
Added Prefect and Matplotlib badges

### PR DESCRIPTION
**Pull request by instabaines**

### CODE REVIEW

**Comment by kohasummons** [comment]
Thank you @instabaines for your contribution. It seems Simple Icons do not have the logos of the badges you added or they have them under a different slug. 

Would you like to review that and perhaps find out what the appropriate slug should be?

**Review by kohasummons — CHANGES_REQUESTED** [review]
☝🏽

**Comment by instabaines** [comment]
@kohasummons 
Yes. I just checked. They are not yet available, but I saw they have been requested already 
https://github.com/simple-icons/simple-icons/issues/6101
https://github.com/simple-icons/simple-icons/issues/3410

**Comment by kohasummons** [comment]
Great! Let's merge this for now then. Thank you @instabaines

**Pull request merged**
