### PR TITLE
Added Alibaba Cloud

### PR DESCRIPTION
**Pull request by debaghosh**
Added the Alibaba Cloud badge under Hosting/Saas section.

### CODE REVIEW

**Comment by mehtaAnsh** [comment]
The badge looks great. Can you just place it above AWS's badge? I will accept the PR then.

**Comment by debaghosh** [comment]
Made the changes.

**Review by mehtaAnsh — COMMENTED** [review]
Looks good! Thanks for adding the badge :)

**Review by mehtaAnsh — APPROVED** [review]
Looks good! Thanks for adding the badge :)

**Pull request merged**
