### PR TITLE
Alphabetically ordering all badges

### PR DESCRIPTION
**Pull request by JakyeRU**
Greetings,

I'm starting a pull request to alphabetically order this repository. If you are willing to contribute please fork [JakyeRU/markdown-badges](https://github.com/JakyeRU/markdown-badges) and open a pull request there.

Thank you.

### CODE REVIEW

**Comment by mehtaAnsh** [comment]
That's great work!

**Comment by JakyeRU** [comment]
I just resolved the conflicts between JakyeRU:master and Ileriayo:master. This pull request is now ready to be merged.

**Review by mehtaAnsh — APPROVED** [review]
Many thanks to @JakyeRU for resolving it alphabetically. We hope to see more major contributions from you! :)

**Comment by Prajwalnazre** [comment]
Awesome work. I too will contribute soon!

**Pull request merged**
