### PR TITLE
[Swagger] icon added

### PR DESCRIPTION
**Pull request by thisisrid**

### CODE REVIEW

**Comment by Abdullah-Alhariri** [comment]
Hi, thank you for contributing.
Can you please update the background color to #85EA2D and set the logo color to white,
that is how we do it here. 

Thanks

**Comment by thisisrid** [comment]
Done, Bg and Icon color Updated

**Review by JakyeRU — APPROVED** [review]
LGTM! Nice job!

**Review by mehtaAnsh — APPROVED** [review]
Thanks for adding the new badge. Keep contributing!

**Pull request merged**
