### PR TITLE
Added TeamCity & ChipperCI

### PR DESCRIPTION
**Pull request by RohanSakhale**

### CODE REVIEW

**Review by Ileriayo — CHANGES_REQUESTED** [review]
Hi @RohanSakhale,

Kindly include the markdown for these badges.
Please see the screenshot below: 
Screenshot 2022-01-11 at 20 10 04

**Comment by RohanSakhale** [comment]
Added markdown syntax as suggested

**Comment by kohasummons** [comment]
Heyy @RohanSakhale! We would really love to have ChipperCI and TeamCity Badge in our stash. Would you like to revisit this PR? ⚡ 

I suggest Creating a new one. Would really save you some time.

**Comment by RohanSakhale** [comment]
Conflicts are now resolved, please re-review

**Review by kohasummons — APPROVED** [review]
Thank you @RohanSakhale For your contributions.

**Pull request merged**
