### PR TITLE
Fix NuxtJS logo and color

### PR DESCRIPTION
**Pull request by 727021**
Adds the missing logo to the NuxtJS badge and colors it to match the color on simple-icons. Here's what the new badge looks like:

NuxtJS

`NuxtJS`

### CODE REVIEW

**Review by Ileriayo — CHANGES_REQUESTED** [review]
Hey Andrew @727021,
Thanks for the contribution, the color and icon looks really good!

Here are the things stopping us from merging:
- the TOC seems out of place where we have Office and Other
- as much as possible, we would like to have really little line changes per PRs
- the additional texts added, really have nothing to do with the logo and color ;) 

It would be the absolute best if this PR was only for the logo and color and then, the other changes moved to another PR.

ProTip: Make simple changes in one PR to have them merged sooner. Best to address a single/simple context at a time.

Can't wait to see the new look on the NuxtJS badge!

**Comment by 727021** [comment]
My editor or an extension must have messed with the TOC and I didn't catch it. I'll get that fixed.

**Comment by 727021** [comment]
@Ileriayo it should be fixed now.

**Review by mehtaAnsh — APPROVED** [review]

**Comment by mehtaAnsh** [comment]
Hey @Ileriayo, I've approved the changes. Can you please just check it out before merging with the main branch? Thanks.

**Comment by mehtaAnsh** [comment]
The PR has been stale for a long time, so I am closing it now. Once the conflicts are fixed, I would be happy to merge.

**Pull request closed without merging**
