### PR TITLE
Added Kaggle badge

### PR DESCRIPTION
**Pull request by joonas-yoon**
Added Kaggle badge in Developer/Forums section

### CODE REVIEW

**Comment by kohasummons** [comment]
Aye @joonas-yoon 👋🏽. This is awwwesome. 🤾🏽 Thank you for bringing kaggle to us. 
I saw the rendered form of the badge and I thought we could do some Improvements on the accessibility side.

🐛 Right now, here's the contrast score using `20beff`
image 


🔨 So I did some tweaking and `035A7D` felt right
image


Would love to hear your thoughts 😃

**Comment by joonas-yoon** [comment]
Hi @kohasummons. it is brand color by kaggle:
https://www.kaggle.com/brand-guidelines

so I think we keep this color. BTW is there rules on the accessibility for badges?

**Comment by kohasummons** [comment]
Hello @joonas-yoon. Thanks for sharing the brand guidelines. 

Well, I noticed something:
- Kaggle used that bright primary color as its logo color. 
- Then a dark background for the logo to lay on.

image

But in our case, we are using:
- The bright primary color as the background
- Then white as the logo/text color.

We should also note that the kaggle logo is barely showing. It seems squished to the side. And Is barely seen in the previous badge.

Further suggestion: 
- One way to go is to replicate the acceptable logo design from kaggle's guidelines, i.e, use a grey background with blue logo.
- I thought of option two, but i can't seem to remember what it is... 😄

**Comment by kohasummons** [comment]
On accessibility and inclusivity with badges design, I don't know. I haven't seen any issue nor discussion talk about it. Yet I feel it's something we should also factor in when making contributions. 

So many people would come across this badges and by putting accessibility into considerations, we can provide a better experience for the majority.

**Comment by joonas-yoon** [comment]
okay I see what you say.
I tried to change background and foreground color to follow your guide, but it is hard to current version of badge by shields.io.

thanks for your reply and i will update this PR

**Review by kohasummons — APPROVED** [review]
🍗 Woohoo! Looks Good To Me.

**Comment by kohasummons** [comment]
🧷 There's an internal war waging in my head on which category "kaggle" should belong to, yet I think at the moment, it might be in the best category right now.  

🤔 Never used kaggle but it feels more like an IDE/EDITOR after spending a brief moment on the site. But If that case is true, then Codepen too would have been hanging out with the wrong folks.

🧠 Just thinking out loud.

**Comment by joonas-yoon** [comment]
right. it is confused. If looking Kaggle as like Jupyter Notebook, it is right in IDE/Editor, but Kaggle has Competition like Codeforces. this is in Developers section :/

**Comment by Ileriayo** [comment]
Hey, I also think Kaggle should come under Forums. It's more than an IDE.

**Comment by kohasummons** [comment]
My lords, **Forum** it is. ⚡

**Pull request merged**
