### PR TITLE
Update: Badge Styles

### PR DESCRIPTION
**Pull request by DalpatRathore**
Hi! @Ileriayo This time I have contributed Badge Styles, as can be seen in the snapshot below. Please review this contribution.

badges

Thanks!

### CODE REVIEW

**Comment by Ileriayo** [comment]
LGTM!

@mehtaAnsh & @kohasummons, any comments?

**Comment by DalpatRathore** [comment]
**Check these variations also!**

## Variation 1 - Numbered
Shields.io offers 5 styles, which are:
1. Plastic   Plastic
2. Flat-square   Flat-square
3. Flat   Flat
4. Social   Social
5. For-the-badge   For-the-badge


## Variation 2 - Only Badges
Shields.io offers 5 styles, which are:
-  Plastic
-  Flat-square
-  Flat
-  Social
-  For-the-badge

## Variation 3 - Table Format
Shields.io offers 5 styles, which are:
| Types | Styles  |
| ---     |  ---      |
| Plastic | Plastic |
| Flat-square |  Flat-square|
| Flat  | Flat |
| Social  |  Social|
| For-the-badge  | For-the-badge|

**Comment by kohasummons** [comment]
Yo! @DalpatRathore 😄 
This is looking good. I absolutely love **variation 3**.
 Neat, nice, and structured.
 Once again, thanks for your contribution 🚀

**Review by kohasummons — COMMENTED** [review]
Looks good 🚀  to me. Let us talk about accessibility.

If you noticed @DalpatRathore I raised an issue on how to make these badges more accessible from a UX standpoint. Check it out here #355 

With that same principle in mind, here's what this badges rank right now on the contrast checker thingy
image

Only Plastic which has a tiny text shadow on the `plastic` text fairs better.

I'm suggesting we use a darker shade of green as the background. Here's the tool I use to check the contrast rating- https://coolors.co/contrast-checker/ffffff-00ff00

Would love to hear your thoughts on this. ⚡

**Comment by DalpatRathore** [comment]
> Yo! @DalpatRathore smile This is looking good. I absolutely love **variation 3**. Neat, nice, and structured. Once again, thanks for your contribution rocket

Hey! @kohasummons, Thanks for appreciating the effort. The commit `Update: Badge Styles` covers only snapshotted arrangement, please do let me know if you want **variation 3** style or arrangement.

**Comment by kohasummons** [comment]
Yes, please! Variation 3.

**Comment by DalpatRathore** [comment]
## Like this :arrow_double_down: 
Shields.io offers 5 styles, which are:
|S. No.| Types | Styles  |
|---| ---     |  ---      |
|1| Plastic | Plastic |
|2| Flat-square |  Flat-square|
|3| Flat  | Flat |
|4| Social  |  Social|
|5| For-the-badge  | For-the-badge|

**Comment by DalpatRathore** [comment]
> Looks good rocket to me. Let us talk about accessibility.
> 
> If you noticed @DalpatRathore I raised an issue on how to make these badges more accessible from a UX standpoint. Check it out here #355
> 
> With that same principle in mind, here's what this badges rank right now on the contrast checker thingy image
> 
> Only Plastic which has a tiny text shadow on the `plastic` text fairs better.
> 
> I'm suggesting we use a darker shade of green as the background. Here's the tool I use to check the contrast rating- https://coolors.co/contrast-checker/ffffff-00ff00
> 
> Would love to hear your thoughts on this. zap

### I totally agree on the accessibility issue :
- Poor Contrast Colors
- Small Size
- Very Small Font Size

**Comment by kohasummons** [comment]
Virtual high five @DalpatRathore :zap: Glad this is looking much better.  
Which do you think would be a much better header for the index numbers?
- S. No.
- S/N

**Comment by kohasummons** [comment]
> ### I totally agree on the accessibility issue :
> * Poor Contrast Colors
> * Small Size
> * Very Small Font Size

I'm super happy you see it that way, please pop into #355 and express your thoughts. 

Meanwhile, @DalpatRathore have you decided on a darker shade for the badges? 🏄🏽

**Comment by DalpatRathore** [comment]
> Virtual high five @DalpatRathore zap Glad this is looking much better. Which do you think would be a much better header for the index numbers?
> 
> * S. No.
> * S/N

S/N

**Comment by kohasummons** [comment]
This is way better! Now even my grandma can see this. 
I was thinking we could retain some of the green and played around till I got this... Thoughts?

Colour: #03650f
Plastic

**Comment by DalpatRathore** [comment]
New Commit Style Format.
<br/>
Capture

**Comment by kohasummons** [comment]
Woohoo! We've come a long way @DalpatRathore but this is bangin' 🎊  Absolutely appreciate your time and contribution. Thanks for adding value. 

@mehtaAnsh @Ileriayo I think this is ready to be merged. comments?

**Comment by Ileriayo** [comment]
I absolutely enjoyed the craftsmanship here.

Thanks, @DalpatRathore & @kohasummons.

I think you should proceed to merge, @kohasummons.

**Comment by Ileriayo** [comment]
Meanwhile, @mehtaAnsh is away for some important work.

**Comment by mehtaAnsh** [comment]
The work looks amazing!

@DalpatRathore and @kohasummons .

Great work here! I think we can proceed with the PR here.

**Comment by DalpatRathore** [comment]
Thanks!,  @kohasummons, @Ileriayo, & @mehtaAnsh

**Pull request merged**
