### PR TITLE
Add Tauri badge

### PR DESCRIPTION
**Pull request by AirOne01**
Badge name: `tauri`
Background color: `#24C8DB`
Logo color: `#FFC131`

### CODE REVIEW

**Comment by AirOne01** [comment]
Refer to #384.

**Comment by kohasummons** [comment]
Thank you @AirOne01! By the way, @AirOne01, I was looking at the badge render and thought perhaps we could have another colour for the logo. Maybe white. What do you think? 

Here's what It should look like:
Tauri

**Comment by AirOne01** [comment]
I reckon, it looks away better.
Let's go with that !

**Comment by kohasummons** [comment]
Fantastic! Alright, send in a PR and I'd merge it right way. :)

**Comment by AirOne01** [comment]
> Fantastic! Alright, send in a PR and I'd merge it right way. :)

Here it is.

**Comment by kohasummons** [comment]
Sweet! Thank you.

**Pull request merged**
