### PR TITLE
Fix YouTube wrong naming

### PR DESCRIPTION
**Pull request by Eloren1**
Youtube to YouTube

### CODE REVIEW

**Comment by mehtaAnsh** [comment]
Hey @Eloren1 ,
Thanks for contributing. Can you please revert all the changes except on YouTube? The reason being people can add their ID's in the **handle** portion. Once reverted, I'll be happy to merge your PR.

**Review by mehtaAnsh — CHANGES_REQUESTED** [review]
Please make the needful changes.

**Review by Eloren1 — COMMENTED** [review]
Sure, sry! Closed previous PR because of this, but forgot to revert changes here

**Review by mehtaAnsh — APPROVED** [review]
Thanks for fixing the typo!

**Pull request merged**
