### PR TITLE
Adding Profile Visitors to Badge

### PR DESCRIPTION
**Pull request by mrhrifat**
### Add a new badge named Profile Visitors
This is my code to **Social** category
```
![ProfileVisitors](https://img.shields.io/badge/Profile%20Visitors-172B4D?style=for-the-badge&logo=Opsgenie&logoColor=white)
```

### CODE REVIEW

**Review by mehtaAnsh — CHANGES_REQUESTED** [review]
Hi @mrhrifat , the profile visitors badge is a little skeptical in my opinion, partly because it uses some other company's logo. If you still consider adding it, please do so in the "Other" section. Thanks for contributing!

**Comment by mrhrifat** [comment]
Hello, Dear @mehtaAnsh . Thanks for your opinion. Actually I didn't find a second logo that would match with the profile's visitors. If you have any such logo in your eyes please let me know, I will definitely change.

**Comment by mrhrifat** [comment]
Hi.. @mehtaAnsh  I review all icon for one time more and about 15-18 logo which can be go with Profile Visitors, I searched them. All the logo have own company. So what do you think, that I can do now?

**Comment by mehtaAnsh** [comment]
> 
> 
> Hello, Dear @mehtaAnsh . Thanks for your opinion. Actually I didn't find a second logo that would match with the profile's visitors. If you have any such logo in your eyes please let me know, I will definitely change.



> 
> 
> Hi.. @mehtaAnsh I review all icon for one time more and about 15-18 logo which can be go with Profile Visitors, I searched them. All the logo have own company. So what do you think, that I can do now?

Hey, I think that we should not take any company's logo and generalize it. That defeats the purpose in my opinion, since the logo is that brand's identity.

**Comment by mrhrifat** [comment]
> Hey, I think that we should not take any company's logo and generalize it. That defeats the purpose in my opinion, since the logo is that brand's identity.

Ok.. Then it's better to close it. Thanks for your support.

**Pull request closed without merging**
