### PR TITLE
Add Clip Paint Studio badge

### PR DESCRIPTION
**Pull request by tkamran**
## Info

|Name|Category|Background Color|Logo Color|
|:--:|:--:|:--:|:--:|
Quill|ORM| `#52B0E7`|`#ffffff`

## Preview

| Badge | url |
| ----- | --- |
| Cisco | `Cisco` |

### CODE REVIEW

**Review by kohasummons — CHANGES_REQUESTED** [review]
Oops! It seems you made a lot of contributions and GitHub is unable to render your code changes. Could you send in another PR for the badge? please. We prefer PRs to comprise single and minimal changes.

**Comment by kohasummons** [comment]
😄  Also, you would really help make the review process easier if you provided more information using the PR template while sending in your changes.

**Comment by tkamran** [comment]
Hi sorry about this I am still learning this process. I will send a new PR soon and will update the description with the correct info

**Comment by Abstaina44** [comment]
Hi brother, lovely GitHub ReadMe.md profile..Keep it up and up we code. cheers

**Pull request closed without merging**
