### PR TITLE
Added ChatGPT Icon to the Artificial Intelligence and Bots Area

### PR DESCRIPTION
**Pull request by Prayag-09**
## Preview

| Badge | URL |
| ----- | --- |
| ChatGPT | `ChatGPT` |

## Screenshot
image

### CODE REVIEW

**Review by kohasummons — CHANGES_REQUESTED** [review]
This looks good. Thanks prayag. We love to have the badges in alphabetical order when we can. Please rearrange the badge to be in order alphabetically and I will merge right away. 😃

**Review by Prayag-09 — COMMENTED** [review]
Arranged according to Alphabetical Order

**Review by kohasummons — APPROVED** [review]
This is what I'm talking about! High-five @Prayag-09. Can't wait to merge more PR from you.

**Comment by Prayag-09** [comment]
Looking forward to it 🤝

**Pull request merged**
