### PR TITLE
Add ResearchGate and ORCID badges

### PR DESCRIPTION
**Pull request by arturofburgos**
Hey I added the ResearchGate and ORCID badges! I do believe that this badges are useful!

### CODE REVIEW

**Review by mehtaAnsh — APPROVED** [review]

**Comment by Ileriayo** [comment]
Hey @arturofburgos,
Kindly resolve conflict holding back the merge.
Thanks for the contribution!

**Review by mehtaAnsh — APPROVED** [review]
Hey Arturo,
Can you please try resolving the conflict?
Thank you for contributing!

**Comment by arturofburgos** [comment]
> Hey Arturo,
> Can you please try resolving the conflict?
> Thank you for contributing!

Hey Ansh, 

Sure, but how can I solve them?

**Comment by mehtaAnsh** [comment]
Hey,
I am not able to open the file for some reason. The conflicts are pretty minor. Just add the badges in the README file. I'll try to look out for solutions as well.

**Comment by arturofburgos** [comment]
> Hey,
> I am not able to open the file for some reason. The conflicts are pretty minor. Just add the badges in the README file. I'll try to look out for solutions as well.

OK! I will do that!

**Comment by mehtaAnsh** [comment]
The PR has been stale for a long time, so I am closing it now. Once the conflicts are fixed, I would be happy to merge.

**Pull request closed without merging**
