### PR TITLE
Added lots of new badges.

### PR DESCRIPTION
**Pull request by MRDGH2821**
Here is the list of changes - 

1. Added Jekyll config which will render the website view of this repo properly.
2. Beautified the file using [Unibeautify](https://unibeautify.com/)
3. Created subcategories for Social section.

New Badges -
1. `Education` sub section, present in Social
2. `Developer/Forums` sub section, present in social (few already existed)
3. Facebook
4. Pinterest
5. Medium
6. Wordpress
7. Ubisoft
8. Square Enix
9. nVIDIA
10. Itch.io
11. PlayStation network

Added badge for Licence section

### CODE REVIEW

**Comment by MRDGH2821** [comment]
Merged PR across forks -
#37 
#31 
#34

**Review by Ileriayo — CHANGES_REQUESTED** [review]
Hello Mihir,
Thanks for adding these badges!

Also, Unibeautify looks great!

Kindly resolve the merge conflicts so that I can proceed to merge.

**Comment by MRDGH2821** [comment]
Merged New commits into my PR & Resolved all conflicts

Created Sub-Sections in few sections. 
There are few Duplicates which are still left out to be removed. 
The lines are so big that Atom editor sometimes gets stuck up and giving me headaches 😅

**Comment by MRDGH2821** [comment]
Removed duplicates & Added sub-section in index itself

**Comment by MRDGH2821** [comment]
Incase there's still something which needs to be done, please do describe the need!

**Review by Ileriayo — APPROVED** [review]
Great work!
Thanks for the effort!

**Pull request merged**
