### PR TITLE
updated and added more badges

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**

### CODE REVIEW

**Review by mehtaAnsh — CHANGES_REQUESTED** [review]
Thanks for all the fixes! Can you please just shift Pandas from Frameworks to ML/DL section? The related libraries are there, so it makes sense for Pandas to go there.

**Comment by gurjeetsinghvirdee** [comment]
> Thanks for all the fixes! Can you please just shift Pandas from Frameworks to ML/DL section? The related libraries are there, so it makes sense for Pandas to go there.

Yeah sure I will fix them!

**Comment by gurjeetsinghvirdee** [comment]
> Thanks for all the fixes! Can you please just shift Pandas from Frameworks to ML/DL section? The related libraries are there, so it makes sense for Pandas to go there.

fixed it

**Review by mehtaAnsh — APPROVED** [review]
Thanks for the changes! Keep contributing :)

**Pull request merged**
